### ISSUE TITLE
tracecontext not propagated if no headers are set

### ISSUE THREAD

**Issue by Flarna** [gadget-inc/opentelemetry-instrumentations#21]
If I don't pass headers to `request` context propagation is not working.

`request("http://localhost:8000/");` => creates a span but traceparent is not transmitted
`request("http://localhost:8000/", { headers: {} });` => creates a span and traceparent is transmitted

I guess the instrumentation needs to add an empty headers object in such cases otherwise there is nothing where `inject` could set the propagation headers.

**Comment by airhorns** [comment]
Thanks for the report! Fixed by #23, released in 0.2.1
